- name: Setup Build Environment
        run: |
          cd ~/rom
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          
          # Dùng bản AOSP chuẩn 64-bit hoặc bản Go edition tiêu chuẩn
          lunch aosp_arm64-userdebug
          
          # Bắt đầu biên dịch
          mka bacon -j4
